name: Build Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.88.0
        target: x86_64-unknown-linux-musl
    
    - name: Build release binary
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Strip binary
      run: strip target/x86_64-unknown-linux-musl/release/totp

    - name: Rename binary
      run: cp target/x86_64-unknown-linux-musl/release/totp totp
    
    - name: Create Release and Upload
      uses: softprops/action-gh-release@v1
      with:
        files: totp